//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonastyrevaBeautifulStydio.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonastirBetyfulStydioEntities : DbContext
    {
        public MonastirBetyfulStydioEntities()
            : base("name=MonastirBetyfulStydioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material> Material { get; set; }
        public DbSet<Proizvoditel> Proizvoditel { get; set; }
        public DbSet<Sotrudnik> Sotrudnik { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Uchet> Uchet { get; set; }
        public DbSet<View_1> View_1 { get; set; }
    }
}
