//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonastyrevaBeautifulStydio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public Nullable<System.DateTime> Detalspol { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Summa { get; set; }
        public int Id { get; set; }
    }
}
